#!/usr/bin/env python3
"""
Integrated Supervisor with Repo Mapper + Code Analyzer
"""
from utils.git_cloner import GitCloner
from utils.code_analyzer import CodeAnalyzer
from pathlib import Path
from datetime import datetime
import json

class IntegratedSupervisor:
    def __init__(self):
        self.cloner = GitCloner()
        self.analyzer = CodeAnalyzer()
    
    def analyze_repository(self, repo_url: str) -> dict:
        print(f"🔍 Integrated Analysis: {repo_url}")
        
        # Step 1: Clone repository
        clone_result = self.cloner.clone_repository(repo_url)
        if not clone_result['success']:
            return clone_result
        
        # Step 2: Code analysis
        analysis_results = self.analyzer.analyze_directory(Path(clone_result['local_path']))
        ccg = self.analyzer.generate_code_context_graph(analysis_results)
        
        # Step 3: Generate comprehensive documentation
        documentation = self.generate_integrated_docs(clone_result, ccg)
        
        # Step 4: Save all results
        output_path = self.save_results(clone_result['repo_name'], documentation, ccg)
        
        return {
            "success": True,
            "repo_name": clone_result['repo_name'],
            "output_path": str(output_path),
            "file_count": clone_result['file_count'],
            'code_analysis': ccg['statistics']
        }
    
    def generate_integrated_docs(self, clone_result: dict, ccg: dict) -> str:
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        doc = f"# {clone_result['repo_name']} - Complete Codebase Analysis\n\n"
        doc += f"*Generated by Codebase Genius on {timestamp}*\n\n"
        
        doc += "## Repository Overview\n\n"
        doc += f"- **Files**: {clone_result['file_count']}\n"
        doc += f"- **README**: {clone_result['readme_found']}\n\n"
        
        doc += "## Code Analysis Results\n\n"
        doc += f"- **Python Files**: {ccg['statistics']['total_files']}\n"
        doc += f"- **Functions**: {ccg['statistics']['total_functions']}\n"
        doc += f"- **Classes**: {ccg['statistics']['total_classes']}\n\n"
        
        doc += "## File Structure\n```\n"
        for file in clone_result['file_tree'][:10]:
            doc += f"{file['path']} ({file['language']})\n"
        doc += "```\n"
        
        if clone_result['readme_found']:
            doc += f"\n## README Preview\n{clone_result['readme_preview']}\n"
        
        return doc
    
    def save_results(self, repo_name: str, documentation: str, ccg: dict) -> Path:
        output_dir = Path("../outputs")
        output_dir.mkdir(exist_ok=True)
        
        docs_file = output_dir / f"{repo_name}_complete_analysis.md"
        docs_file.write_text(documentation)
        
        ccg_file = output_dir / f"{repo_name}_code_context_graph.json"
        ccg_file.write_text(json.dumps(ccg, indent=2))
        
        return docs_file

def main():
    supervisor = IntegratedSupervisor()
    test_repo = "https://github.com/psf/requests"
    
    print("Integrated Supervisor")
    result = supervisor.analyze_repository(test_repo)
    
    if result['success']:
        print(f"Success: {result['repo_name']}")
        print(f"Output: {result['output_path']}")

if __name__ == "__main__":
    main()
